---
# tasks file for provisioning
- name: "Upload SSH key"
  digital_ocean_sshkey:
    oauth_token: "{{ oauth_token }}"
    name: "{{ key.name }}"
    ssh_pub_key: "{{ item }}"
    state: present
  with_file: "{{ key.path }}"
  register: result

- name: Fact SSH Key
  digital_ocean_sshkey_facts:
    oauth_token: "{{ oauth_token }}"

- name: Setando SSH Key na variavel
  set_fact:
    pubkey: "{{ item.id }}"
  loop: "{{ ssh_keys|json_query(ssh_pubkey) }}"
  vars:
    ssh_pubkey: "[?name=='{{ key.name }}']"

- debug:
    msg: "{{ pubkey }}"


- name: Criando droplet na Digital Ocean
  digital_ocean_droplet:
    state: present
    name: "{{ droplet_name }}"
    oauth_token: "{{ oauth_token }}"
    size: "{{ size }}"
    region: "{{ region }}"
    image: "{{ image }}"
    ssh_keys: [ "{{ pubkey }}" ] 
    wait_timeout: 500
  register: deploy

- debug:
    msg: "ID is {{ deploy.data.droplet.id }}, IP is {{ deploy.data.ip_address }}"

- name: Verificando se o droplet esta presente
  digital_ocean_droplet:
    state: present
    id: "{{ deploy.data.droplet.id }}"
    name: "{{ droplet_name }}"
    oauth_token: "{{ oauth_token }}"
    size: "{{ size }}"
    region: "{{ region }}"
    image: "{{ image }}"
    wait_timeout: 500


- name: Adicionando usuário administrador
  user:
    name: "{{ user_ssh }}"
    comment: "{{ user_ssh_name }}"

- name: Set authorized key taken from file
  authorized_key:
    user: "{{ user_ssh }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

