---
# tasks file for provisioning
- name: "Upload SSH key"
  digital_ocean_sshkey:
    oauth_token: "{{ oauth_token }}"
    name: "{{ key.name }}"
    ssh_pub_key: "{{ item }}"
    state: present
  with_file: "{{ key.path }}"
  no_log: true
  register: result

- name: Fact SSH Key
  digital_ocean_sshkey_info:
    oauth_token: "{{ oauth_token }}"
  register: ssh_keys

- name: Setando SSH Key na variavel
  set_fact:
    pubkey: "{{ item.public_key }}"
  loop: "{{ ssh_keys.data|json_query(ssh_pubkey) }}"
  vars:
    ssh_pubkey: "[?name=='{{ key.name }}']"
  no_log: true

- debug:
    msg: "{{ pubkey }}"

- name: Criando droplet na Digital Ocean
  digital_ocean_droplet:
    state: present
    name: "{{ droplet_name }}"
    oauth_token: "{{ oauth_token }}"
    size: "{{ size }}"
    region: "{{ region }}"
    image: "{{ image }}"
    # ssh_keys: [ "{{ pubkey }}" ] 
    wait_timeout: 500
  register: deploy

- name: Verificando se o droplet esta presente
  digital_ocean_droplet:
    state: present
    id: "{{ deploy.data.droplet.id }}"
    name: "{{ droplet_name }}"
    oauth_token: "{{ oauth_token }}"
    size: "{{ size }}"
    region: "{{ region }}"
    image: "{{ image }}"
    wait_timeout: 500

- debug:
    msg: "DropletId: {{ deploy.data.droplet.id }}, IP: {{ deploy.data.ip_address }}"


